version: '2'

services:
  opa:
    image: openpolicyagent/opa:latest
    ports:
      - 8181:8181
    # WARNING: OPA is NOT running with an authorization policy configured. This
    # means that clients can read and write policies in OPA. If you are
    # deploying OPA in an insecure environment, be sure to configure
    # authentication and authorization on the daemon. See the Security page for
    # details: https://www.openpolicyagent.org/docs/security.html.
    volumes:
      - ./policy/permissions.rego:/policy.rego
    command:
      - "run"
      - "--server"
      - "--log-level=debug"
      - "/policy.rego"
